### ISSUE TITLE
Warning: Could not find file /Panako/build/logging.properties to copy.

### ISSUE THREAD

**Issue by Johndirr** [JorenSix/Panako#10]
When following the installation guide on http://panako.be/releases/Panako-latest/readme.html#getting_started a warning occurs when executing ant install. Is this a problem?

**Comment by matrix3301** [comment]
I got the same issue as you. And I cannot know how to go on.

**Comment by dime13016** [comment]
hi, 
"touch logging.properties", solved the problem for me.

**Comment by JorenSix** [comment]
I have moved the default instal location of the new version of Panako to the home directory of the user to avoid problems such as these. Thanks for the report.
