### ISSUE TITLE
I succeed  store sound track into dbs, but can't query matching music

### ISSUE THREAD

**Issue by matrix3301** [JorenSix/Panako#11]
I have already installed Panako on my Mac OSx, and succeed stored some sound tracks for testing.
panako stats
Number of audio objects: 4
Number of fingerprints: 296
Number of seconds: 58.0
Number of fingerprints/second: 5.103448275862069

But, when I make a query testing. It's only the totally same with original sound can be matched. Beyond that, any cutting fragment sound from original sound cannot be matched.

panako query ser.m4a
Query;Query start (s);Query stop (s); Match Identifier;Match description; Match start (s); Match score; Time factor (%); Frequency factor(%)
/Users/rex/Desktop/ser.m4a;0;2;null;null;-1;-1;-1%;-1%

And I use panako browse, I can get the fragment is matching. How can I use this, thanks a lot
<img width="722" alt="image" src="https://user-images.githubusercontent.com/9948802/47006301-2c9b9d80-d168-11e8-998b-1f1f4c0b3870.png">

**Comment by matrix3301** [comment]
I have resolved.

**Comment by dime13016** [comment]
> I have resolved.

Hi,
I have the same problem, how did you solve it please ?

**Comment by dime13016** [comment]
Ok only 5min max audios are working.

**Comment by xaw-roz** [comment]
> I have resolved.

How did you resolve

**Comment by arun164** [comment]
> I have resolved.

Can you please explain how did you resolve ?

**Comment by JorenSix** [comment]
Please try the same with the new version of Panako: it is a complete rewrite.
