### ISSUE TITLE
Please add functionality to remove file from the database

### ISSUE THREAD

**Issue by RobSis** [JorenSix/Panako#12]
I'm not sure how hard would it be, but it would be really beneficial for my use-case.

Thank you for this amazing piece of software!

**Comment by JorenSix** [comment]
Panako version 2 now has a delete command which completely removes all fingerprints form a database. Note however that for the database a tree structure is used and deleting many fingerprints could lead to unbalanced trees with sub-par performance. The performance under many deletes has not been properly tested.
