### ISSUE TITLE
PanakoStrategy.java typo Line 372?

### ISSUE THREAD

**Issue by lucasso44** [JorenSix/Panako#33]
In PanakoStrategy.java line 372 reads:

```java
timeFactor < Config.getFloat(Key.PANAKO_MAX_FREQ_FACTOR)
```
Should read:

```java
frequencyFactor < Config.getFloat(Key.PANAKO_MAX_FREQ_FACTOR)
```

**Comment by JorenSix** [comment]
Fixed,

[See this commit](https://github.com/JorenSix/Panako/commit/d1c595be4ca620aa71f3852b9cdbd54a4ee77b5c)

Thanks for the bug report.
