### ISSUE TITLE
Fingerprint matching and DB init

### ISSUE THREAD

**Issue by alejandrojapkin** [JorenSix/Panako#4]
1. I'm testing Panako from a docker image with this config NFFT_MAPDB_DATABASE=/opt/panako/dbs/nfft_panako_db
There's no such db file

2. Is it possible to sort a list of fingerprints by similarity rather than just look for an exact match?

**Comment by julianterzyk** [comment]
Regarding your first question: Two things ... does the directory /opt/panako/dbs exist? Are you testing via "panako store track.mp3" or what are you exactly doing?

**Comment by julianterzyk** [comment]
Well there will be no nfft_panako_db file if you have not fingerprinted any track yet. The issue sounds like a permission problem to me. Can you try to run the test again, but before to `chown -R username /opt/panako/`. Maybe only root has access currently.

**Comment by julianterzyk** [comment]
Regarding the second question: I don't think this is possible out of the box, but would need some deeper digging and own adaptions of Joren's code.

**Comment by arungoyal** [comment]
I have tried with "chown -R username /opt/panako/" as well but the same issue I am facing.

**Comment by vineetmultitv** [comment]
I got the same issue, just ensure there is no permission issue and yes, create dbs directory manually under /opt/panako/. It will generate the .db file automatically.

**Comment by arungoyal** [comment]
yes issue got resolved by creating dbs directory.But I am not able to get fingerprint of any mp3 or wav file. I have tried with multiple file 

Number of audio objects: 5
Number of fingerprints: 0
Number of seconds: 0.0
Number of fingerprints/second: NaN

Above response I m getting from stats command.

Do I need to change in the config file ?

Attached are some logs if this can help in issue


[logs.txt](https://github.com/JorenSix/Panako/files/1947454/logs.txt)

**Comment by princepft** [comment]
I am also facing same issue. After creating dbs folder, audio/video are getting processed but fingerprint are not getting generated. Please suggest if found any workaround.
Number of audio objects: 2
Number of fingerprints: 0
Number of seconds: 0.0
Number of fingerprints/second: NaN

**Comment by dhambri** [comment]
You probably need to install ffmpeg.

**Comment by JorenSix** [comment]
ffmpeg is indeed needed. To make this more clear I have changed the default setting to only use a single CPU core by default which provides clearer error messages.
